### ISSUE TITLE
[API] limit and before

### ISSUE THREAD

**Issue by madmaniak** [chanks/sequel-seek-pagination#1]
Thank you @chanks for this gem. It's really simple and effective implementation with nice improvements. I'm wondering if you thought about _before_ functionality - as we want to check if there are any new elements at the top of collection. We can now achieve it by a hack using <code>reverse</code> method twice on our dataset - directly after <code>order</code> and then after <code>seek_paginate</code>:

```ruby
DB[:table].order(:id).reverse.seek_paginate(10, after: 3).reverse.all
# SELECT * FROM "table" WHERE ("id" < 3) ORDER BY "id" ASC LIMIT 10
```
That will change where id comparison direction but null corner case is not covered.

Another thing is that ```seek_paginate``` method could be just ```seek``` and we could apply limit the same as we do with ```order``` - by using default Sequel API:

```ruby
DB[:table].order(:id).limit(10).seek(after: 3).all
```
What do you think? I will use it anyway. Cheers!

**Comment by chanks** [comment]
Hi @madmaniak, thank you for the kind words. I like your suggestions - unfortunately, you caught me just as I'm about to leave for a two-week vacation, so I won't be able to dig into this until I get back, but I'll leave this open so that I remember to get to it then.

Thanks again!

**Comment by bangcht** [comment]
Hi @madmaniak, thank for your trick :+1:, but my mate and me took an example and figured out that your code should be:
`DB[:table].order(:id).reverse.seek_paginate(10, after: 3).all.reverse`
`reverse` should perform after `all`

Cheers!

**Comment by madmaniak** [comment]
Cool @chanks I'm glad you like it.
@bangcht if you use it after <code>all</code> you operate on an Array. Is it not working for you? If so try to update gems (pg, sequel, sequel_pg and this).

**Comment by madmaniak** [comment]
Never mind @chanks you're right. My implementation is naive and only for simple cases. Considering limited size of an array it's not so bad to use reverse at least temporarily.

**Comment by madmaniak** [comment]
https://github.com/chanks/sequel-seek-pagination/pull/2

**Comment by chanks** [comment]
So I tweaked the API, since I wasn't wild about it. It now looks like:

```ruby
# limit is applied elsewhere, or not, but it's really an unrelated concern
DB[:items].order(:column1, :column2).seek(value: [1, 5])
# Or:
DB[:items].order(:column1, :column2).seek(pk: 89)
# By default these look for values greater than what you pass in, so if you also want to include an item with values [1, 5] you would do:
DB[:items].order(:column1, :column2).seek(value: [1, 5], include_exact_match: true)
```

I've been thinking about the reverse issue, and I'm not sure there's a better way to do it than to just call #reverse on the dataset before #seek. And if that's all that that option is going to do, I think we don't even really need it.

What do you guys think?

**Comment by madmaniak** [comment]
Cool! I've just realized that it could be just:

```ruby
Dataset.seek(89)
# or
Dataset.seek([1, 5])
```
and use proper method basing on type.

**Comment by chanks** [comment]
How? The pk and order columns could each be of any type.

**Comment by madmaniak** [comment]
If Array then value else pk.

**Comment by chanks** [comment]
Ah, I see what you mean, but the model could have a composite primary key.
And if someone wants to sort by a single column, I think it should be fine
for them to just pass in values without wrapping them in arrays.

**Comment by madmaniak** [comment]
Like I said it could be additional so you can use it both ways.

**Comment by chanks** [comment]
Yeah, I suppose, but I think it would make the API too complicated.

I'm going to close this, and try switching an app over to master and seeing how that feels before I release a new version. And I suppose I'll need to update the docs too.
